### ISSUE TITLE
内存使用

### ISSUE THREAD

**Issue by kaousi** [diduweiwu/wechat-reader-ext#1]
时间越长会占用内存越大， 并不能自动释放

**Comment by diduweiwu** [comment]
> 

之前在MAC Edge上有遇到过这个问题.后面加入了定时刷新页面就会释放内存. 我当时分析的是微信读书页面的锅,即使没有插件,手动去切换阅读页面,内存也会越来越大
如果还有的话,希望可以把对应环境信息提供一下哇?

**Comment by kaousi** [comment]
![image](https://user-images.githubusercontent.com/52817545/164467099-4e0bf038-cde6-4678-89c1-0dc2c0c81562.png)
我配置了强制刷新插件才可以降低内存

**Comment by diduweiwu** [comment]
> 

嗯呐,这个问题现在貌似不明显了,刚发了新版插件.我主要用的chrome.回头试试看Edge哈
