### ISSUE TITLE
麻烦更新下greasyfork里的此脚本

### ISSUE THREAD

**Issue by EchoGroot** [diduweiwu/wechat-reader-ext#3]
[greasyfork](https://greasyfork.org/zh-CN/scripts/411508-%E5%88%B7%E5%BE%AE%E4%BF%A1%E8%AF%BB%E4%B9%A6%E7%9A%84%E6%97%B6%E9%97%B4)

**Comment by diduweiwu** [comment]
> 
(⊙o⊙)…额老哥,这个greasyfork脚本不是我开发的, 我的是这个 [微信读书-WEB端自动阅读插件](https://greasyfork.org/zh-CN/scripts/407535-%E5%BE%AE%E4%BF%A1%E8%AF%BB%E4%B9%A6-web%E7%AB%AF%E8%87%AA%E5%8A%A8%E9%98%85%E8%AF%BB%E6%8F%92%E4%BB%B6)

**Comment by EchoGroot** [comment]
搞错了 那是我安装的另一个（不能用），你那个我也安装了的，很好使！👍👍👍
