### ISSUE TITLE
缩小chrome页面显示, 工具失效; 放大正常

### ISSUE THREAD

**Issue by lllong33** [diduweiwu/wechat-reader-ext#4]
首先感谢 author 提供这么人性化的功能; 
可能是一些拙见, 无法显示微信读书自有功能栏切换; 只能显示插件工具栏了~

**Comment by diduweiwu** [comment]
> 

对的,微信读书页面缩小比例后就会失效一致无限切换页面.这个问题还没有找到方法解决...

无法显示微信读书自有功能栏切换; 只能显示插件工具栏了: 请问下这个可以上个图或者视频看看哇?
