### ISSUE TITLE
请问怎么重置设置或者删除本地设置持久化文件？重新安装脚本没用

### ISSUE THREAD

**Issue by lanceyliao** [diduweiwu/wechat-reader-ext#6]
如题

**Comment by lanceyliao** [comment]
已解决，删除cookie后配置就重置了。

但脚本和https://greasyfork.org/zh-CN/scripts/436914
有冲突。
作者可以参考他这个脚本（感觉断更了）的页面文字自动展开方式（更宽），现在我是两个脚本都装着的

**Comment by diduweiwu** [comment]
嗯哈老哥，进入weread.com 页面，F12然后在Localstorage下有个config属性，删除就好了。回头我加个开关进行清楚吧。页面文字自动展示这个我得学习下他的脚本。因为我现在没咋用浏览器看书，所以脚本 不怎么更新啦🤣
![screenshot-20240108-093849](https://github.com/diduweiwu/wechat-reader-ext/assets/6733790/f035a14a-7986-45a2-b781-108f924cabbd)
